knp_paginator:
  page_range: 5         # Nombre de pages affichées dans la pagination
  default_options:
    page_name: page    # Nom du paramètre dans l'URL (ex: ?page=2)
    sort_field_name: sort  # Paramètre pour le tri
    sort_direction_name: direction # Sens du tri
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'  # Utilisation de Bootstrap 5
