security:
    # Password hashers configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers configuration to load users from the database
    providers:
        users_database:
            entity:
                class: App\Entity\User
                property: email  # Utilise l'email comme identifiant

    firewalls:
        # Configuration pour l'environnement de développement (profiler, WDT, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ 
            security: false

        # Configuration principale pour l'application
        main:
            lazy: true
            provider: users_database  # Utilise le provider pour charger les utilisateurs depuis la base de données
            form_login:
                login_path: app_login  # Nom de la route pour la page de connexion
                check_path: app_login  # Nom de la route pour le traitement du formulaire de connexion
                default_target_path: app_category  # Redirection après connexion réussie
                username_parameter: _username  # Vérifie que le champ du formulaire est bien nommé "_username"
                password_parameter: password  # Vérifie que le champ du formulaire est bien nommé "password"
            logout:
                path: app_logout
                target: app_login # Redirige vers la page de login après déconnexion
                invalidate_session: true
            entry_point: App\Security\GoogleAuthenticator
                
    # Access control rules
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }  # Accès réservé aux administrateurs
        - { path: ^/logout, roles: ROLE_USER }  # Accès réservé aux utilisateurs connectés
        - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }  # Assure-toi que l'utilisateur doit être connecté pour accéder à son profil
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Permet l'accès à la route de déconnexion pour tous les utilisateurs, même non authentifiés
        - { path: ^/user/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }