security:
    # Password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider
    providers:
        users_database:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_database

            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\CustomLoginSuccessHandler
                username_parameter: _username
                password_parameter: password

            custom_authenticator: App\Security\GoogleAuthenticator
            entry_point: App\Security\GoogleAuthenticator

            logout:
                path: app_logout
                target: app_login
                invalidate_session: true

    access_control:
        # Routes publiques
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS }

        # Routes protégées
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }

        # Déconnexion accessible aux utilisateurs connectés
        - { path: ^/logout, roles: IS_AUTHENTICATED_REMEMBERED }

        # Inscription publique
        - { path: ^/user/new, roles: PUBLIC_ACCESS }
