controllers:
    resource: ../src/Controller/
    type: attribute

question_show:
    path: /question/{id}.{_format}
    controller: App\Controller\QuestionController::show
    defaults:
        _format: html
    methods: GET