parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Enum\RoleEnum: ~

    HWI\Bundle\OAuthBundle\OAuth\OAuthUtils: '@hwi_oauth.oauth_utils'

    App\Security\CustomLoginSuccessHandler:
        arguments:
            $router: '@router'
