parameters:
    product_photos_directory: '%kernel.project_dir%/public/uploads/products'
    reclamation_uploads_directory: '%kernel.project_dir%/public/uploads/photos'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Explicit service definition for OAuthUtils
    HWI\Bundle\OAuthBundle\OAuth\OAuthUtils: '@hwi_oauth.oauth_utils'